=== crocs-muni/seccerts-overlay/Specification/Schemas/seccertsMetaDataBindingSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "data": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "timestamp": {
                            "type": "string"
                        },
                        "certificate_ids": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "metadata_header_url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "timestamp",
                        "certificate_ids",
                        "metadata_header_url"
                    ]
                }
            ]
        },
        "author": {
            "type": "string"
        },
        "version": {
            "type": "string"
        },
        "JWT": {
            "type": "string"
        }
    },
    "required": [
        "data",
        "author",
        "version",
        "JWT"
    ]
}

=== crocs-muni/seccerts-overlay/Demonstration Bindings/demonstration_binding.json
{
    "data": [
        {
            "timeStamp": "2023-05-05 22:15:39.549131",
            "certificate_ids": [
                "2247",
                "NSCIB-CC-13-37760-CR2"
            ],
            "metadata_header_url": "https://raw.githubusercontent.com/crocs-muni/seccerts-overlay/main/Demonstration%20Bindings/demonstration_data_header.json"
        }
    ],
    "author": "CROCS",
    "version": "1.0",
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjpbeyJ0aW1lU3RhbXAiOiIyMDIzLTA1LTA1IDIyOjE1OjM5LjU0OTEzMSIsImNlcnRpZmljYXRlX2lkcyI6WyIyMjQ3IiwiTlNDSUItQ0MtMTMtMzc3NjAtQ1IyIl0sIm1ldGFkYXRhX2hlYWRlcl91cmwiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vY3JvY3MtbXVuaS9zZWNjZXJ0cy1vdmVybGF5L21haW4vRGVtb25zdHJhdGlvbiUyMEJpbmRpbmdzL2RlbW9uc3RyYXRpb25fZGF0YV9oZWFkZXIuanNvbiJ9XSwiYXV0aG9yIjoiQ1JPQ1MiLCJ2ZXJzaW9uIjoiMS4wIn0.QRpXlsrMHhae1oHxcDvzYIX6-FLfh3oNGcMVeNKcNCM"
}

=== crocs-muni/seccerts-overlay/Demonstration Bindings/Bindings/demonstration_binding.json
{
    "data": [
        {
            "timestamp": "2023-05-05 22:27:47.508185",
            "certificate_ids": [
                "NIST-2247",
                "NSCIB-CC-13-37760-CR2"
            ],
            "metadata_header_url": "https://raw.githubusercontent.com/crocs-muni/seccerts-overlay/main/Demonstration%20Bindings/demonstration_data_header.json"
        }
    ],
    "author": "CROCS",
    "version": "1.0",
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjpbeyJ0aW1lc3RhbXAiOiIyMDIzLTA1LTA1IDIyOjI3OjQ3LjUwODE4NSIsImNlcnRpZmljYXRlX2lkcyI6WyJOSVNULTIyNDciLCJOU0NJQi1DQy0xMy0zNzc2MC1DUjIiXSwibWV0YWRhdGFfaGVhZGVyX3VybCI6Imh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9jcm9jcy1tdW5pL3NlY2NlcnRzLW92ZXJsYXkvbWFpbi9EZW1vbnN0cmF0aW9uJTIwQmluZGluZ3MvZGVtb25zdHJhdGlvbl9kYXRhX2hlYWRlci5qc29uIn1dLCJhdXRob3IiOiJDUk9DUyIsInZlcnNpb24iOiIxLjAifQ.u3PaNTo7-xp-EKhUk_qGlkNujFHR78UvE_KamyPEmbE"
}

=== crocs-muni/seccerts-overlay/Examples/Bindings/example_binding_1.json
{
    "data": [
        {
            "timeStamp": "2023-04-12 18:04:32.030376",
            "certificateIDs": [
                "SERTIT-116"
            ],
            "metadataHeaderURL": "https://raw.githubusercontent.com/crocs-muni/seccerts-overlay/main/Examples/Headers/example_header_0.json"
        },
        {
            "timeStamp": "2023-04-12 18:04:32.083464",
            "certificateIDs": [
                "NSCIB-CC-0031318-CR2",
                "NSCIB-CC-0031318-CR3"
            ],
            "metadataHeaderURL": "file:///C:/Dokumenty/Diplomovka/seccerts-overlay/Examples/Headers/example_header_1.json"
        }
    ],
    "author": "CROCS",
    "version": "1.0",
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjpbeyJ0aW1lU3RhbXAiOiIyMDIzLTA0LTEyIDE4OjA0OjMyLjAzMDM3NiIsImNlcnRpZmljYXRlSURzIjpbIlNFUlRJVC0xMTYiXSwibWV0YWRhdGFIZWFkZXJVUkwiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vY3JvY3MtbXVuaS9zZWNjZXJ0cy1vdmVybGF5L21haW4vRXhhbXBsZXMvSGVhZGVycy9leGFtcGxlX2hlYWRlcl8wLmpzb24ifSx7InRpbWVTdGFtcCI6IjIwMjMtMDQtMTIgMTg6MDQ6MzIuMDgzNDY0IiwiY2VydGlmaWNhdGVJRHMiOlsiTlNDSUItQ0MtMDAzMTMxOC1DUjIiLCJOU0NJQi1DQy0wMDMxMzE4LUNSMyJdLCJtZXRhZGF0YUhlYWRlclVSTCI6ImZpbGU6Ly8vQzovRG9rdW1lbnR5L0RpcGxvbW92a2Evc2VjY2VydHMtb3ZlcmxheS9FeGFtcGxlcy9IZWFkZXJzL2V4YW1wbGVfaGVhZGVyXzEuanNvbiJ9XSwiYXV0aG9yIjoiQ1JPQ1MiLCJ2ZXJzaW9uIjoiMS4wIn0.gKxSdBhrVvWbs_QkY3WupMJRCc8sOvhZDd-D4lvWUL4"
}
